### PR TITLE
Fix misspelling retrift to retrofit, and reformat code

### LINKED ISSUE #50: misspelling retrift  --> retrofit
https://github.com/googlecodelabs/kotlin-coroutines/blob/326868689e4ebb2aa9193186dc24515b0a852d27/coroutines-codelab/start/src/main/java/com/example/android/kotlincoroutines/main/TitleRepository.kt#L54

### PR DESCRIPTION
**Pull request by StanleyKou**
- Fixes #50 retfift to retrofit
- Reformat code

### CODE REVIEW

File: coroutines-codelab/start/src/main/java/com/example/android/kotlincoroutines/main/TitleRepository.kt [hunk 1]
```diff
@@ -51,7 +51,7 @@ class TitleRepository(val network: MainNetwork, val titleDao: TitleDao) {
      * the current tile.
      */
     fun refreshTitleWithCallbacks(titleRefreshCallback: TitleRefreshCallback) {
-        // This request will be run on a background thread by retrift
+        // This request will be run on a background thread by retrofit
```
Comment (StanleyKou) [inline coroutines-codelab/start/src/main/java/com/example/android/kotlincoroutines/main/TitleRepository.kt]: Typo correction

File: coroutines-codelab/start/src/main/java/com/example/android/kotlincoroutines/main/TitleRepository.kt [hunk 2]
```diff
@@ -51,7 +51,7 @@ class TitleRepository(val network: MainNetwork, val titleDao: TitleDao) {
      * the current tile.
      */
     fun refreshTitleWithCallbacks(titleRefreshCallback: TitleRefreshCallback) {
```
Comment (StanleyKou) [inline coroutines-codelab/start/src/main/java/com/example/android/kotlincoroutines/main/TitleRepository.kt]: https://codelabs.developers.google.com/codelabs/kotlin-coroutines/index.html?index=..%2F..index#8

In the codelab section 9 said,
> Delete the `refreshTitleCallbacks` function as it is not used anymore.

But the real function name is `refreshTitleWithCallbacks`. 
In my opinion, `refreshTitleWithCallbacks` seems much better name, because it exactly explains what it does.
How about replacing `refreshTitleCallbacks` by `refreshTitleWithCallbacks` in the codelab?

**Comment by StanleyKou** [comment]
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgooglecodelabs%2Fkotlin-coroutines%2Fpull%2F58) for more info**.

@googlebot I signed it!

**Comment by StanleyKou** [comment]
@googlebot I signed it!

File: coroutines-codelab/start/src/main/java/com/example/android/kotlincoroutines/main/TitleRepository.kt (hunk 2 above)
Comment (objcode) [reply coroutines-codelab/start/src/main/java/com/example/android/kotlincoroutines/main/TitleRepository.kt]: Will update text, thanks!
